apiVersion: apps/v1
kind: Deployment
metadata:
  name: phishing-deployment
  namespace: phishing-detection
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phishing
  template:
    metadata:
      labels:
        app: phishing
    spec:
      containers:
        - name: phishing-container
          image: anitalluri00/phishing-detection-ps:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: phishing-config
          volumeMounts:
            - name: phishing-storage
              mountPath: /data
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: phishing-storage
          persistentVolumeClaim:
            claimName: phishing-pvc
