apiVersion: apps/v1
kind: Deployment
metadata:
  name: phishing-app
  namespace: phishing-detection
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phishing-app
  template:
    metadata:
      labels:
        app: phishing-app
    spec:
      containers:
      - name: phishing-container
        image: anitalluri00/phishing-detection-ps:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: phishing-config
        volumeMounts:
        - name: app-storage
          mountPath: /app/data
      volumes:
      - name: app-storage
        persistentVolumeClaim:
          claimName: phishing-pvc
