apiVersion: apps/v1
kind: Deployment
metadata:
  name: phishing-detection-deployment
  namespace: phishing-detection
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phishing-detection
  template:
    metadata:
      labels:
        app: phishing-detection
    spec:
      containers:
        - name: phishing-detection
          image: anitalluri00/phishing-detection-ps:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: phishing-config
          volumeMounts:
            - name: phishing-storage
              mountPath: /app/data
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: phishing-storage
          persistentVolumeClaim:
            claimName: phishing-pvc
