apiVersion: apps/v1
kind: Deployment
metadata:
  name: phishing-detection
  namespace: phishing-detection
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phishing-detection
  template:
    metadata:
      labels:
        app: phishing-detection
    spec:
      containers:
      - name: phishing-detection
        image: anitalluri00/phishing-detection-ps
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: phishing-config
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        volumeMounts:
        - name: phishing-storage
          mountPath: /data
      volumes:
      - name: phishing-storage
        persistentVolumeClaim:
          claimName: phishing-pvc
