apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phishing-ingress
  namespace: phishing-detection
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: phishing.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: phishing-service
                port:
                  number: 80
