apiVersion: v1
kind: Service
metadata:
  name: phishing-service
  namespace: phishing-detection
spec:
  type: LoadBalancer
  selector:
    app: phishing-app
  ports:
  - port: 80
    targetPort: 5000
